# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  Configuration: "Release"

steps:
  - checkout: self
    fetchDepth: 0 # Don't do shallow clone, for SonarQube
  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'ravikumar-cybage'
      scannerMode: 'dotnet'
      projectKey: 'ravikumar-cybage_SonarCloud'
      projectName: 'SonarCloud'
      extraProperties: |
        # Additional properties that will be passed to the scanner, put one key=value per line

        # Disable Multi-Language analysis
        sonar.scanner.scanAll=false

        # Configure location of the OpenCover report
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/results/coverage.opencover.xml
        sonar.coverage.exclusions=**/*Test.cs
        sonar.internal.debug=false
  
  - task: DotNetCoreCLI@2
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "Tests/Tests.csproj"
      arguments: "/p:CollectCoverage=true /p:CoverletOutput=results/coverage"

  - script: ls -alR ./Tests
    displayName: "List results directory"

  - task: SonarCloudAnalyze@3
    inputs:
      jdkversion: "JAVA_HOME_17_X64"

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: "300"

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: "$(Build.SourcesDirectory)/Tests/results/coverage.opencover.xml"
      failIfCoverageEmpty: true





# steps:

# - checkout: self
#   fetchDepth: 0  

# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     version: '8.0.x'

# - task: DotNetCoreCLI@2
#   displayName: 'Restore'
#   inputs:
#     command: 'restore'
#     projects: 'unit-testing-using-dotnet-test.sln'

# # - task: SonarCloudPrepare@3
# #   inputs:
# #     SonarCloud: 'SonarCloud'
# #     organization: 'ravikumar-cybage'
# #     scannerMode: 'dotnet'
# #     projectKey: 'ravikumar-cybage_finance-service'
# #     projectName: 'finance-service'
# #     extraProperties: |
# #       sonar.scanner.scanAll=false
# #       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml
# #       sonar.coverage.exclusions=**/*Test.cs
# # - task: DotNetCoreCLI@2
# #   displayName: 'Build'
# #   inputs:
# #     command: 'build'
# #     projects: 'unit-testing-using-dotnet-test.sln'
# #     arguments: '--configuration Release'

# # EXACT test command from docs
# - task: DotNetCoreCLI@2
#   displayName: 'Test with Coverage'
#   inputs:
#     command: 'test'
#     projects: 'PrimeService.Tests/PrimeService.Tests.csproj'
#     arguments: '--configuration Release /p:CollectCoverage=true /p:CoverletOutput=results/coverage /p:CoverletOutputFormat=opencover'
#     publishTestResults: true


# - task: SonarCloudAnalyze@3
#   inputs:
#     jdkversion: 'JAVA_HOME_17_X64'

# - task: SonarCloudPublish@3
#   inputs:
#     pollingTimeoutSec: '300'

# - task: PublishCodeCoverageResults@2
#   displayName: 'Publish Code Coverage Results'
#   inputs:
#     codeCoverageTool: 'opencover'   # required
#     summaryFileLocation: '$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml'
#     failIfCoverageEmpty: true


